### ISSUE TITLE
browserify support?

### ISSUE THREAD

**Issue by stevenvachon** [jsdom/whatwg-url#53] opened 2016-08-05 02:42 UTC
This lib is written with ES6, so it doesn't get parsed correctly with browserify:
```
Parse error at -:3082,12
SyntaxError: Unexpected token: name (x)
Error
```
It'd be great if there were a browser version available to serve as a polyfill for IE.

**Comment by stevenvachon** [comment] 2016-08-05 15:08
Hello?

**Comment by SEAPUNK** [comment] 2016-08-05 15:11
Give it time; this issue isn't even a day old.

**Comment by domenic** [comment] 2016-08-05 15:13
This sounds like a browserify bug, that it can't parse ES6.

**Comment by stevenvachon** [comment] 2016-08-05 15:14
It's actually an uglifyjs bug. Just noticed that when I took uglify out of the stream.

**Comment by SEAPUNK** [comment] 2016-08-05 15:14
Yeah, uglify doesn't support ES6 just yet. I don't use Browserify myself, but you could give https://github.com/babel/babelify a look to convert any ES6 code to ES5.

**Comment by domenic** [comment] 2016-08-05 15:15
Cool. Not much for us to do here I guess, so closing.

**Closed by domenic** 2016-08-05 15:15 UTC

**Comment by stevenvachon** [comment] 2016-08-05 15:43
Thanks, @SEAPUNK. babelify worked, but I ended up needing a `Symbol` polyfill to complete the build. I'm just going to use the polymer `URL` polyfill for my browser tests.

**Comment by stevenvachon** [comment] 2016-08-08 02:28
@domenic if I were to submit a PR that adds `devDependencies` and an npm script to build a browserified file, what're the odds of it getting merged?

**Comment by domenic** [comment] 2016-08-08 02:33
I don't think that's the responsibility of a library. Browserify works fine on this library; there's no need for a script. It sounds like your problems have more to do with compatibility with older browsers, and that's a non-goal for us (we encourage consumers to use the appropriate tools for their environments, but we as the producers don't want to cater to all).

**Comment by stevenvachon** [comment] 2016-08-08 02:37
Having to set up such tools for each of my libraries isn't fun. I guess that I could release a "url-polyfill" package, then.

**Comment by domenic** [comment] 2016-08-08 02:57
Generally you don't want, as a library author, to be making these sorts of decisions for your customers. Such tools belong on the app level.

**Comment by stevenvachon** [comment] 2017-02-22 18:15
Running this module through Browserify results in a very large (79kb gzipped) file. TR46 seems to be the cause. Would removing this for a browser build only lose spec-compliance for IDNAs?

**Comment by domenic** [comment] 2017-02-22 18:22
Skimming the spec it seems like TR46 is only used for domain-related stuff, not search params-related stuff.

**Comment by stevenvachon** [comment] 2017-02-22 18:25
What are your thoughts on allowing URLs with invalid domains to be parsed without error?

**Comment by domenic** [comment] 2017-02-22 18:28
It's not just parsed without error; it's the lack of punycode conversion, e.g. `https://faß.ExAmPlE/` should parse and then serialize to `https://xn--fa-hia.example/`.

Whether that's OK depends on your use case; I'm not familiar with it.

**Comment by stevenvachon** [comment] 2017-02-22 18:34
my use case: https://github.com/stevenvachon/isomorphic-url

**Comment by stevenvachon** [comment] 2017-02-22 18:39
TR46 removed the need for [punycode](https://npmjs.com/punycode), correct? Perhaps the browser build could run that after parsing

**Comment by stevenvachon** [comment] 2017-03-02 19:27
What is the reason for the punycode conversion? Wouldn't `fetch`/`XmlHttpRequest`/`http.request` still support those chars?

**Comment by Sebmaster** [comment] 2017-03-02 19:31
If you use urls in the browser, it'll do url resolution internally. But the APIs won't expose the resulting URL. If URL is unavailable, whatwg-url needs to be able to do the full thing.

**Comment by domenic** [comment] 2017-03-02 19:35
Again, the issue is about use cases. (A library is not a use case; a use case is something that an actual consumer wants to accomplish.)

I can't think of any use cases for using whatwg-url that involve feeding the result into APIs like fetch. Those already do URL resolution, so whatwg-url is useless there.

The main use cases for this library are derived from the jsdom project, whose use cases are around scraping and testing. For such cases, it's important in general that reading back `el.href` or `new URL(...).href` be accurate compared to what's in the browser.

It's not clear what your use cases are (or what the use cases of users using your isomorphic-url package are), so it's not clear whether whatwg-url is even right for them.

**Comment by stevenvachon** [comment] 2017-03-02 19:39
My library's use case is to use `URL` in the browser for any general use case. But 78kb gzipped is not practical.

**Comment by domenic** [comment] 2017-03-02 19:40
That's not a use case...

**Comment by stevenvachon** [comment] 2017-03-02 19:43
Sure it is. I'd say that this project's use case is to provide a spec-compliant `URL` implementation for any general use case, in line with how browsers currently or will eventually perform. My use case is the same, except there is a file size limitation because it's not just for the server.

**Comment by domenic** [comment] 2017-03-02 19:45
OK, I don't want to get into a semantics argument about how you're using the word "use case" incorrectly. So let's just take what you say at face value. In that case I think whatwg-url is not a good fit for your project.

**Comment by Sebmaster** [comment] 2017-03-02 19:55
> My use case is the same, except there is a file size limitation because it's not just for the server.

You can't be spec compliant without tr46, so you'll have to come to some kind of trade-off here.

**Comment by stevenvachon** [comment] 2017-03-02 20:20
I was not suggesting that TR46 be removed from this project, but wondered what kind of functionality would break and under what circumstances if it were excluded from a browser shim. I may have misunderstood, but I think that this is an accurate example:

```js
const pageUrl = location.href; // https://xn--fa-hia.example/
const linkUrl = document.querySelector("a").href; // https://faß.ExAmPlE/

if (new shimmedURL(pageUrl).hostname !== new shimmedURL(linkUrl)) {
    // false negative
}
```

**Comment by Sebmaster** [comment] 2017-03-02 20:56
Yes. Hostnames will break in general if they use unicode (you'll be missing normalization, punycode, etc). If you just need your library to resolve paths correctly, it'll work fine with a tr46 shim.

**Comment by stevenvachon** [comment] 2017-03-13 19:37
I now have tr46 shimmed with punycode and `toLowerCase()`. Does this still break anything? I understand that invalid IDNAs will not be rejected, but such errors can also be discovered in a request attempt.

**Comment by domenic** [comment] 2017-03-13 20:07
Yes, it means you parse URLs different than browsers or the spec.

**Comment by stevenvachon** [comment] 2017-03-13 20:09
I realize this. But how different? I'd like to document the caveats.

**Comment by stevenvachon** [comment] 2017-03-14 14:08
The spec mentions that case-folding is different than lowercasing , "particularly" for [Cherokee characters](http://www.unicode.org/reports/tr46/#Mapping). Are there others?

**Comment by stevenvachon** [comment] 2017-03-15 13:46
@domenic @Sebmaster ^

**Comment by stevenvachon** [comment] 2017-03-19 20:02
😕

**Comment by hollowdoor** [comment] 2017-06-24 23:10
> It's not clear what your use cases are (or what the use cases of users using your isomorphic-url package are), so it's not clear whether whatwg-url is even right for them.

I would use it in an isomorphic router to get a url pathname, and query from a string to match against. I found this issue because I was looking for a solution to that actually.

Right now a check for `window && (URL || createFromLInk) || module && module.exports && (require('url')).URL || myCustomURLConstructor` is how I'm doing it. Which at least works for the time being.
