### ISSUE TITLE
URL is not a constructor

### ISSUE THREAD

**Issue by israelidanny** [jsdom/whatwg-url#99] opened 2017-07-17 10:56 UTC
I'm trying to work with this library. When I try to use it in a `new URL(url)` way, it says:
Type Error: URL is not a constructor

When I try to use it as function, it says:
Type Error: Failed to construct 'URL'. Please use the 'new' operator; this constructor cannot be called as a function.

I'm using node `v6.10.3`

**Comment by domenic** [comment] 2017-07-17 18:21
Can you please produce complete example code, that I can run with `node example.js`?

**Comment by herodrigues** [comment] 2017-07-19 01:48
Same problem here. 

```
[herinson@arch guru-chrome]$ node
> URL = require('whatwg-url')
{ URL: [Function: URL],
  URLSearchParams: [Function: URLSearchParams],
  parseURL: [Function],
  basicURLParse: [Function],
  serializeURL: [Function: serializeURL],
  serializeHost: [Function: serializeHost],
  serializeInteger: [Function],
  serializeURLOrigin: [Function],
  setTheUsername: [Function],
  setThePassword: [Function],
  cannotHaveAUsernamePasswordPort: [Function: cannotHaveAUsernamePasswordPort],
  percentDecode: [Function: percentDecode] }
> new URL('https://saraiva.com.br')
TypeError: URL is not a constructor
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:278:10)
    at REPLServer.Interface._line (readline.js:625:8)
> URL('https://saraiva.com.br')
TypeError: URL is not a function
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:278:10)
    at REPLServer.Interface._line (readline.js:625:8)
> 
```

**Comment by stevenvachon** [comment] 2017-07-19 01:52
```js
const {URL} = require('whatwg-url');

new URL("http://host/");
```

**Comment by stevenvachon** [comment] 2017-07-19 01:52
const {URL} = require('whatwg-url');

new URL('http://host/');

**Comment by stevenvachon** [comment] 2017-07-19 01:53
```js
const {URL} = require('whatwg-url');

new URL('http://host/');
```

**Comment by stevenvachon** [comment] 2017-07-19 01:54
Use [universal-url](https://npmjs.com/universal-url), anyway.

**Comment by domenic** [comment] 2017-07-19 02:33
Closing since it appears people forgpt to use the URL export.

Deleting comments advertising other modules.

**Closed by domenic** 2017-07-19 02:33 UTC

**Comment by israelidanny** [comment] 2017-07-19 05:13
What do you mean forgot to use URL export? Isn't that what Steven is doing?

**Comment by domenic** [comment] 2017-07-19 05:19
Yes. But it's not what @herodrigues or, probably, you, are doing.

**Comment by israelidanny** [comment] 2017-07-19 09:08
Why assume things and close the issue prematurely? I did exactly what @stevenvachon did, and had the error.

Also if you notice in my case, the error seems to be self contradictory - with a `new` keyword it complains about one thing, and without that same keyword - the opposite.

The code is as minimal as:
```javascript
const {URL} = require('whatwg-url');
new URL('http://host/');
```

I also tried:
```javascript
const whatWG = require('whatwg-url');
new whatWG.URL('http://host/');
```

**Comment by TimothyGu** [comment] 2017-07-19 10:35
@israelidanny Can you provide the stack trace to either of those?

**Comment by domenic** [comment] 2017-07-19 11:23
I closed because I cannot reproduce the issue: https://runkit.com/embed/ehem42xx4dnp

**Comment by devaffair** [comment] 2018-02-25 17:22
Why close?  I have the exact same problem, and I AM using the export.

**Comment by domenic** [comment] 2018-02-25 17:33
In that case you'll need to provide a RunKit example like I did above, that contains no external dependencies and is stripped down to its minimal components, to illustrate the bug in this library.
