### ISSUE TITLE
Punycode domains are not properly validated

### ISSUE THREAD

**Issue by karwa** [jsdom/whatwg-url#239] opened 2022-05-02 07:07 UTC
Start with the input:

`http://xn--ls8h/`

It works, as it should, and the result is the same. It's the poop emoji, in case you were wondering. It's in the WPT tests.

Anyway, we can just start adding text to the end of this. For example:

```
(Input) -> (JSDOM output)

"http://xn--ls8h=/" -> "http://xn--js8hea/"
"http://xn--ls8h==/" -> "http://xn--hs8hdh/"
"http://xn--ls8h===/" -> "http://xn--gs8hcfj/"

"http://xn--ls8h===helloworldhowareyoutoday/" -> "http://xn--gs8hcaceekclworldhowareyoutoday/"
                   ^^^^^^^^^^^^^^^^^^^^^^^^                              ^^^^^^^^^^^^^^^^^^^
```

All of these inputs are invalid. Safari refuses to parse them, and my own IDNA implementation agrees. The tail part of the Punycode domain (after the `xn--`) should only consist of ASCII alphanumerics; having `"="` signs in there (in the input) is clearly invalid.

**Comment by domenic** [comment] 2022-05-03 14:42
Any help diagnosing where in whatwg-url (or perhaps https://github.com/jsdom/tr46/) this is breaking would be much appreciated. As usual, the goal is to match specs as 1:1 as possible so this kind of diagnostic would probably look like: "here is the spec, it says X. But your code is doing Y."

**Comment by annevk** [comment] 2023-01-16 14:34
I also noticed `https://ي./` failing, but succeeding in browsers. I would write a WPT, but I think that currently gives UB due to UTS46 handling of CheckBidi so it would require some kind of `tentative` test I suppose.

**Comment by domenic** [comment] 2023-01-23 03:05
The cases in the OP seem to get fixed by https://github.com/mathiasbynens/punycode.js/pull/124 .

`https://ي./` still fails.

A few hundred other cases from https://github.com/web-platform-tests/wpt/pull/38080 still fail. Will comment over there.

**Comment by TimothyGu** [comment] 2023-01-24 04:57
The issue with `https://ي./` is that the [Bidi Rule](https://www.rfc-editor.org/rfc/rfc5893.html#section-2) in RFC 5893 seems to just assume that any label is nonempty (see e.g., rule 1). The bug can thus be reproduced with any domain name with both a RTL character and an empty label.

Ideally, UTS 46 should clarify this point, excluding empty labels from Bidi Rule consideration. We should add this item to https://github.com/whatwg/url/issues/744 if there's still time.

**Comment by annevk** [comment] 2023-01-24 06:22
That's the second comment there, right? Already submitted.

**Comment by TimothyGu** [comment] 2023-01-24 06:24
Ah, right.

**Closed** 2023-03-08 07:03 UTC
